In [1]:
import pandas as pd
from hhData import hhData

In [2]:
files = [str(i) + 'ds.json' for i in range(1, 29)]

hh_data = hhData()
vacancies = pd.DataFrame.from_dict(hh_data.load_data(files))

100%|██████████| 28/28 [03:10<00:00,  6.80s/it]

In [3]:
vacancies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 226219 entries, 0 to 226218
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   name             226219 non-null  object
 1   area             226219 non-null  object
 2   key_skills       226219 non-null  object
 3   published_at     226219 non-null  object
 4   specializations  226219 non-null  object
 5   profarea_name    226219 non-null  object
dtypes: object(6)
memory usage: 10.4+ MB

In [4]:
vacancies

,name,area,key_skills,published_at,specializations,profarea_name
0,Старший менеджер интернет-проектов / интернет-...,Москва,[],2019-07-09T16:16:07+0300,"[1.359, 1.89, 12.5, 3.90]","[3, 12, 1]"
1,Java-разработчик,Санкт-Петербург,"[Java, GWT, HTML, SQL, Google Maps Api, Git, J...",2019-06-17T11:24:57+0300,[1.221],[1]
2,Middle Frontend Developer (Angular),Санкт-Петербург,[],2019-07-17T11:25:28+0300,[1.221],[1]
3,Специалист по IT Отдела поддержки пользователе...,Тараз,[],2019-06-17T11:25:23+0300,"[1.221, 1.327, 1.420, 1.395]",[1]
4,Ведущий продуктовый аналитик/Senior Product An...,Москва,"[Product Management, Управление продуктом, Раз...",2019-07-17T11:25:45+0300,"[1.327, 1.25, 3.150, 1.89, 5.368, 1.474]","[3, 1, 5]"
...,...,...,...,...,...,...
226214,SQL разработчик,Москва,"[MySQL, HTML, Коммуникабельность, Целеустремле...",2020-02-10T14:20:02+0300,"[1.221, 1.274, 1.420, 1.82, 1.50, 1.270]",[1]
226215,Mobile-Frontend developer (Vue),Новосибирск,"[JavaScript, AngularJS, jQuery, Less, Adobe Ph...",2019-12-13T17:29:12+0300,[1.221],[1]
226216,Process developer (SQL),Химки,"[MS SQL, Analytical skills, Databases, Process...",2019-12-31T09:51:32+0300,"[1.221, 1.536, 1.327, 1.25, 1.50]",[1]
226217,Team lead JavaScript/ Senior Developer (Витрина),Москва,"[REST, HTTP, Hibernate ORM, PostgreSQL, JavaSc...",2020-02-11T09:11:46+0300,"[1.221, 1.272, 1.327, 1.395]",[1]
226218,Администратор БД,Киев,"[Linux, Shell Scripting, Работа с базами данны...",2020-01-22T15:35:46+0300,"[1.273, 1.536, 1.211, 1.25, 1.420, 1.82]",[1]